export const GET_ERRORS="GET_ERRORS";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const GET_EXPENSES ="GET_EXPENSES";
export const EXPENSE_LOADING ="EXPENSE_LOADING";
export const EXPENSE_NOT_FOUND="EXPENSE_NOT_FOUND";
export const CLEAR_CURRENT_USER="CLEAR_CURRENT_USER";